# Generated by Django 3.2.13 on 2022-10-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
